version: '3.9'
services:
  db:
    image: docker.io/postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lotemodb_dev
    ports:
      - '5051:5432'
    volumes:
      - lotemo_pgdata:/var/lib/postgresql/data

  s3:
    image: docker.io/dxflrs/garage:v1.0.1
    container_name: garage
    restart: unless-stopped
    ports:
      - '3900:3900'
      - '3901:3901'
      - '3902:3902'
      - '3903:3903'
    volumes:
      - ./garage.toml:/etc/garage.toml
      - s3-meta:/var/lib/garage/meta
      - s3-data:/var/lib/garage/data

volumes:
  lotemo_pgdata:
  s3-meta:
  s3-data:
